name: Smaple GitHub Actions
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  job1:  
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        run: echo "git checkout"
      - name: building
        run: echo "building the project"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: pushing to docket
        run: echo "pushed to the docker container"
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: K8S deployment
        run: echo "Application is running in k8s"
