name: upstream
on:
  workflow_dispatch:
jobs:
   build_job:
      runs-on: ubuntu-latest
      steps:
        - name: printing hello
          run: echo "hello"
        - name: Downstream Job
          run: echo "Calling Downstream job"
